// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: pb/sample.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloPersonMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  uint32 `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *HelloPersonMessageRequest) Reset() {
	*x = HelloPersonMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sample_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloPersonMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloPersonMessageRequest) ProtoMessage() {}

func (x *HelloPersonMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sample_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloPersonMessageRequest.ProtoReflect.Descriptor instead.
func (*HelloPersonMessageRequest) Descriptor() ([]byte, []int) {
	return file_pb_sample_proto_rawDescGZIP(), []int{0}
}

func (x *HelloPersonMessageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloPersonMessageRequest) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type HelloPersonMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HelloMessage string `protobuf:"bytes,1,opt,name=hello_message,json=helloMessage,proto3" json:"hello_message,omitempty"`
}

func (x *HelloPersonMessageResponse) Reset() {
	*x = HelloPersonMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sample_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloPersonMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloPersonMessageResponse) ProtoMessage() {}

func (x *HelloPersonMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sample_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloPersonMessageResponse.ProtoReflect.Descriptor instead.
func (*HelloPersonMessageResponse) Descriptor() ([]byte, []int) {
	return file_pb_sample_proto_rawDescGZIP(), []int{1}
}

func (x *HelloPersonMessageResponse) GetHelloMessage() string {
	if x != nil {
		return x.HelloMessage
	}
	return ""
}

var File_pb_sample_proto protoreflect.FileDescriptor

var file_pb_sample_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0x41, 0x0a, 0x19, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x61, 0x67, 0x65, 0x22, 0x41, 0x0a, 0x1a,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0x5d, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x54, 0x0a, 0x0b, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_sample_proto_rawDescOnce sync.Once
	file_pb_sample_proto_rawDescData = file_pb_sample_proto_rawDesc
)

func file_pb_sample_proto_rawDescGZIP() []byte {
	file_pb_sample_proto_rawDescOnce.Do(func() {
		file_pb_sample_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_sample_proto_rawDescData)
	})
	return file_pb_sample_proto_rawDescData
}

var file_pb_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_sample_proto_goTypes = []interface{}{
	(*HelloPersonMessageRequest)(nil),  // 0: sample.HelloPersonMessageRequest
	(*HelloPersonMessageResponse)(nil), // 1: sample.HelloPersonMessageResponse
}
var file_pb_sample_proto_depIdxs = []int32{
	0, // 0: sample.Hello.HelloPerson:input_type -> sample.HelloPersonMessageRequest
	1, // 1: sample.Hello.HelloPerson:output_type -> sample.HelloPersonMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_sample_proto_init() }
func file_pb_sample_proto_init() {
	if File_pb_sample_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_sample_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloPersonMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sample_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloPersonMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_sample_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_sample_proto_goTypes,
		DependencyIndexes: file_pb_sample_proto_depIdxs,
		MessageInfos:      file_pb_sample_proto_msgTypes,
	}.Build()
	File_pb_sample_proto = out.File
	file_pb_sample_proto_rawDesc = nil
	file_pb_sample_proto_goTypes = nil
	file_pb_sample_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	HelloPerson(ctx context.Context, in *HelloPersonMessageRequest, opts ...grpc.CallOption) (*HelloPersonMessageResponse, error)
}

type helloClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloClient(cc grpc.ClientConnInterface) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) HelloPerson(ctx context.Context, in *HelloPersonMessageRequest, opts ...grpc.CallOption) (*HelloPersonMessageResponse, error) {
	out := new(HelloPersonMessageResponse)
	err := c.cc.Invoke(ctx, "/sample.Hello/HelloPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	HelloPerson(context.Context, *HelloPersonMessageRequest) (*HelloPersonMessageResponse, error)
}

// UnimplementedHelloServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServer struct {
}

func (*UnimplementedHelloServer) HelloPerson(context.Context, *HelloPersonMessageRequest) (*HelloPersonMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloPerson not implemented")
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_HelloPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloPersonMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).HelloPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample.Hello/HelloPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).HelloPerson(ctx, req.(*HelloPersonMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sample.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloPerson",
			Handler:    _Hello_HelloPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/sample.proto",
}
